version: "3.8"

services:
  # --- INFRASTRUCTURE (Databases) ---
  kafka:
    image: confluentinc/confluent-local:7.5.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "8082:8082"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test:
        [
          "CMD",
          "kafka-topics",
          "--bootstrap-server",
          "localhost:9092",
          "--list",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka
    networks:
      - app_network

  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network


  # --- BACKEND API (NestJS Monolith) ---
  api:
    image: ${DOCKERHUB_USERNAME:-amalviya0907}/event-booking-api:latest
    container_name: event-booking-api
    ports:
      - "4000:4000" # API Gateway Port
    depends_on:
      kafka:
        condition: service_healthy
      mongo:
        condition: service_started
    environment:
      - PORT=4000
      - KAFKA_BROKERS=kafka:29092
      - AUTH_DB_URI=mongodb://mongo:27017/auth_db
      - BOOKING_DB_URI=mongodb://mongo:27017/booking_db
      - EVENT_DB_URI=mongodb://mongo:27017/event_db
    networks:
      - app_network

  # --- FRONTEND (Next.js) ---
  web:
    image: ${DOCKERHUB_USERNAME:-amalviya0907}/event-booking-web:latest
    container_name: event-booking-web
    ports:
      - "3000:3000" # Client Port
    environment:
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://localhost:4000 # Configured for host to access the gateway
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  kafka_data:
  mongo_data:
